### Importing libraries and dataset

In [1]:
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.metrics import mean_absolute_percentage_error
from sklearn.linear_model import LinearRegression, Ridge
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from optuna.visualization import (
    plot_optimization_history,
    plot_parallel_coordinate,
    plot_param_importances
)
from xgboost import XGBRegressor
from sklearn.svm import SVR
import pandas as pd
import numpy as np
import dagshub
import mlflow
import optuna
import tqdm

c:\Users\Lenovo\miniconda3\envs\uber\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
from sklearn import set_config

set_config(transform_output="pandas")

In [ ]:
# set the dagshub tracking server

mlflow.set_tracking_uri("https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow")
dagshub.init(repo_owner='mrvivekkumar7171', repo_name='uber-demand-prediction', mlflow=True)

In [5]:
# load the training and test data

train_data_path = "../data/processed/train.csv"
test_data_path = "../data/processed/test.csv"

train_df = pd.read_csv(train_data_path, parse_dates=["tpep_pickup_datetime"]).set_index("tpep_pickup_datetime")
test_df = pd.read_csv(test_data_path, parse_dates=["tpep_pickup_datetime"]).set_index("tpep_pickup_datetime")
train_df

,lag_1,lag_2,lag_3,lag_4,region,total_pickups,avg_pickups,day_of_week
tpep_pickup_datetime,,,,,,,,
2016-01-01 01:00:00,160.0,149.0,120.0,58.0,0,187,161.0,4
2016-01-01 01:15:00,187.0,160.0,149.0,120.0,0,194,175.0,4
2016-01-01 01:30:00,194.0,187.0,160.0,149.0,0,180,177.0,4
2016-01-01 01:45:00,180.0,194.0,187.0,160.0,0,197,185.0,4
2016-01-01 02:00:00,197.0,180.0,194.0,187.0,0,185,185.0,4
...,...,...,...,...,...,...,...,...
2016-02-29 22:45:00,15.0,9.0,11.0,11.0,29,12,12.0,0
2016-02-29 23:00:00,12.0,15.0,9.0,11.0,29,17,14.0,0
2016-02-29 23:15:00,17.0,12.0,15.0,9.0,29,15,14.0,0
2016-02-29 23:30:00,15.0,17.0,12.0,15.0,29,15,15.0,0
2016-02-29 23:45:00,15.0,15.0,17.0,12.0,29,12,14.0,0

### Preparing the dataset

In [6]:
# missing value in training data

train_df.isna().sum()

lag_1            0
lag_2            0
lag_3            0
lag_4            0
region           0
total_pickups    0
avg_pickups      0
day_of_week      0
dtype: int64

In [7]:
# missing values in the test data

test_df.isna().sum()

lag_1            0
lag_2            0
lag_3            0
lag_4            0
region           0
total_pickups    0
avg_pickups      0
day_of_week      0
dtype: int64

In [8]:
# make X_train and y_train

X_train = train_df.drop(columns=["total_pickups"])
y_train = train_df["total_pickups"]

In [9]:
X_train.head()

,lag_1,lag_2,lag_3,lag_4,region,avg_pickups,day_of_week
tpep_pickup_datetime,,,,,,,
2016-01-01 01:00:00,160.0,149.0,120.0,58.0,0,161.0,4
2016-01-01 01:15:00,187.0,160.0,149.0,120.0,0,175.0,4
2016-01-01 01:30:00,194.0,187.0,160.0,149.0,0,177.0,4
2016-01-01 01:45:00,180.0,194.0,187.0,160.0,0,185.0,4
2016-01-01 02:00:00,197.0,180.0,194.0,187.0,0,185.0,4

In [10]:
# make X_test and y_test

X_test = test_df.drop(columns=["total_pickups"])
y_test = test_df["total_pickups"]

In [11]:
X_test.head()

,lag_1,lag_2,lag_3,lag_4,region,avg_pickups,day_of_week
tpep_pickup_datetime,,,,,,,
2016-03-01 00:00:00,36.0,44.0,31.0,29.0,0,39.0,1
2016-03-01 00:15:00,41.0,36.0,44.0,31.0,0,37.0,1
2016-03-01 00:30:00,35.0,41.0,36.0,44.0,0,41.0,1
2016-03-01 00:45:00,47.0,35.0,41.0,36.0,0,38.0,1
2016-03-01 01:00:00,34.0,47.0,35.0,41.0,0,35.0,1

### Hyperparameter tuning and model selection

In [12]:
# encode the data

encoder = ColumnTransformer([
    ("ohe", OneHotEncoder(drop="first", sparse_output=False), ["region", "day_of_week"])
], remainder="passthrough", n_jobs=-1)

In [13]:
encoder

ColumnTransformer(n_jobs=-1, remainder='passthrough',
                  transformers=[('ohe',
                                 OneHotEncoder(drop='first',
                                               sparse_output=False),
                                 ['region', 'day_of_week'])])

In [14]:
# encode the train and test data

X_train_encoded = encoder.fit_transform(X_train)
X_test_encoded = encoder.transform(X_test)

In [15]:
# set the experiment

mlflow.set_experiment("Model Selection")

<Experiment: artifact_location='mlflow-artifacts:/b6b4d8f3b62643e39281e1bb68a431be', creation_time=1782047742355, effective_trace_archival_retention=None, experiment_id='0', last_update_time=1782047742355, lifecycle_stage='active', name='Model Selection', tags={'mlflow.experimentKind': 'custom_model_development'}, trace_location=None, workspace='default'>

In [ ]:
def objective(trial):
    # start the child run
    with mlflow.start_run(nested=True) as child:
        
        # model name search space
        list_of_models = ["LR", "RF", "GBR", "XGBR"]
        model_name = trial.suggest_categorical("model_name", list_of_models)

        # we can also use time series model for train the model like ARIMA, SARIMA etc.
    
        if model_name == "LR":
            model = LinearRegression()
    
        elif model_name == "RF":
            n_estimators_rf = trial.suggest_int("n_estimators_rf", 10, 100, step=10)
            max_depth_rf = trial.suggest_int("max_depth_rf", 3, 10)
            model = RandomForestRegressor(n_estimators=n_estimators_rf, max_depth=max_depth_rf, random_state=42, n_jobs=-1)
    
        elif model_name == "GBR":
            n_estimators_gb = trial.suggest_int("n_estimators_gb", 10, 100, step=10)
            learning_rate_gb = trial.suggest_float("learning_rate_gb", 1e-4, 1e-1, log=True)
            model = GradientBoostingRegressor(n_estimators=n_estimators_gb, learning_rate=learning_rate_gb, random_state=42)
    
        elif model_name == "XGBR":
            n_estimators_xgb = trial.suggest_int("n_estimators_xgb", 10, 100, step=10)
            learning_rate_xgb = trial.suggest_float("learning_rate_xgb", 1e-4, 1e-1, log=True)
            max_depth_xgb = trial.suggest_int("max_depth_xgb", 3, 10)
            model = XGBRegressor(n_estimators=n_estimators_xgb, learning_rate=learning_rate_xgb, max_depth=max_depth_xgb)
    
        # log the model name
        mlflow.log_param("model_name", model_name)
        
        # log the model parameters
        mlflow.log_params(model.get_params())
        
        # fit on the data
        model.fit(X_train_encoded, y_train)
    
        # get the predictions
        y_pred = model.predict(X_test_encoded)
    
        # calculate the loss
        loss = mean_absolute_percentage_error(y_test, y_pred)
    
        # log the metric
        mlflow.log_metric("MAPE", loss)
        return loss

In [17]:
# optimize the objective function

with mlflow.start_run(run_name="best_model", nested=True) as parent:

    # create a study object
    study = optuna.create_study(study_name="model_selection", direction="minimize")
    # optimize the objective function
    study.optimize(func=objective, n_trials=50, n_jobs=-1)
    
    # log the best parameters
    mlflow.log_params(study.best_params)
    # log the best error value
    mlflow.log_metric("Best_MAPE", study.best_value)

[I 2026-06-21 19:30:26,796] A new study created in memory with name: model_selection

🏃 View run zealous-doe-162 at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0/runs/8aa08b01011541c2a9e7cee5f5b61db4
🧪 View experiment at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0

[I 2026-06-21 19:30:31,985] Trial 2 finished with value: 0.07934790285463093 and parameters: {'model_name': 'LR'}. Best is trial 2 with value: 0.07934790285463093.

🏃 View run auspicious-bat-82 at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0/runs/56be401f72fe47d6ac1fc18da9716b02
🧪 View experiment at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0

[I 2026-06-21 19:30:32,386] Trial 3 finished with value: 0.07934790285463093 and parameters: {'model_name': 'LR'}. Best is trial 2 with value: 0.07934790285463093.

🏃 View run lyrical-flea-405 at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0/runs/779646ace1c54889b9aa73c109b0c580
🧪 View experiment at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0

[I 2026-06-21 19:30:34,702] Trial 0 finished with value: 5.557977199554443 and parameters: {'model_name': 'XGBR', 'n_estimators_xgb': 70, 'learning_rate_xgb': 0.002453862765512489, 'max_depth_xgb': 5}. Best is trial 2 with value: 0.07934790285463093.

🏃 View run dashing-gnat-614 at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0/runs/e71019c0950b486e9e1452dd79ba7550
🧪 View experiment at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0
🏃 View run salty-sponge-852 at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0/runs/3446a971526c470d83befbbd5f61821f
🧪 View experiment at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0
🏃 View run bustling-penguin-211 at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0/runs/cb8e8bfc089e4756af9dece20212cfc5
🧪 View experiment at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0

[I 2026-06-21 19:30:53,805] Trial 6 finished with value: 6.562803745269775 and parameters: {'model_name': 'XGBR', 'n_estimators_xgb': 20, 'learning_rate_xgb': 0.0001185944267647683, 'max_depth_xgb': 3}. Best is trial 2 with value: 0.07934790285463093.
[I 2026-06-21 19:30:56,419] Trial 1 finished with value: 5.022170351669708 and parameters: {'model_name': 'GBR', 'n_estimators_gb': 30, 'learning_rate_gb': 0.009581920359091532}. Best is trial 2 with value: 0.07934790285463093.
[I 2026-06-21 19:31:00,166] Trial 4 finished with value: 0.17760074065667272 and parameters: {'model_name': 'RF', 'n_estimators_rf': 30, 'max_depth_rf': 7}. Best is trial 2 with value: 0.07934790285463093.

🏃 View run rambunctious-kit-87 at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0/runs/4704187cf5ee4b878f33eb37fa121401
🧪 View experiment at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0
🏃 View run wistful-smelt-245 at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0/runs/ff8bfc7fb99347b994fb1201e8a6e8b3
🧪 View experiment at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0

[I 2026-06-21 19:31:20,181] Trial 5 finished with value: 0.14190337045245785 and parameters: {'model_name': 'RF', 'n_estimators_rf': 80, 'max_depth_rf': 9}. Best is trial 2 with value: 0.07934790285463093.

🏃 View run thoughtful-boar-750 at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0/runs/90d0df52bc634126bc3c1743e7832ac2
🧪 View experiment at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0

[I 2026-06-21 19:34:22,824] Trial 8 finished with value: 5.398821830749512 and parameters: {'model_name': 'XGBR', 'n_estimators_xgb': 90, 'learning_rate_xgb': 0.002340168570267139, 'max_depth_xgb': 3}. Best is trial 2 with value: 0.07934790285463093.
[I 2026-06-21 19:34:25,074] Trial 9 finished with value: 0.07934790285463093 and parameters: {'model_name': 'LR'}. Best is trial 2 with value: 0.07934790285463093.

🏃 View run nosy-squid-557 at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0/runs/5a7b6628ef7744fa9c8478195522c6bc
🧪 View experiment at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0

[I 2026-06-21 19:34:33,437] Trial 12 finished with value: 6.385870456695557 and parameters: {'model_name': 'XGBR', 'n_estimators_xgb': 100, 'learning_rate_xgb': 0.00030154543352652426, 'max_depth_xgb': 5}. Best is trial 2 with value: 0.07934790285463093.

🏃 View run gaudy-grouse-894 at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0/runs/ba401ab3522c4cb9a8246dc66cda4fe0
🧪 View experiment at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0

[I 2026-06-21 19:34:38,190] Trial 13 finished with value: 0.07934790285463093 and parameters: {'model_name': 'LR'}. Best is trial 2 with value: 0.07934790285463093.

🏃 View run powerful-bug-286 at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0/runs/4a769f8dba394ab7ac8718ad1bb67a4a
🧪 View experiment at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0

[I 2026-06-21 19:34:43,281] Trial 14 finished with value: 0.07934790285463093 and parameters: {'model_name': 'LR'}. Best is trial 2 with value: 0.07934790285463093.

🏃 View run rumbling-crab-932 at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0/runs/38d153db36e6484883a1079768077818
🧪 View experiment at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0

[I 2026-06-21 19:34:56,096] Trial 10 finished with value: 6.310345278082078 and parameters: {'model_name': 'GBR', 'n_estimators_gb': 70, 'learning_rate_gb': 0.000628369017714487}. Best is trial 2 with value: 0.07934790285463093.

🏃 View run shivering-slug-200 at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0/runs/e7cc6774ae724174befadd1cebcd4967
🧪 View experiment at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0
🏃 View run clumsy-wren-726 at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0/runs/0905f78bc3bd44dea57113f90bd8c69a
🧪 View experiment at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0

[I 2026-06-21 19:35:04,097] Trial 11 finished with value: 6.449617895065355 and parameters: {'model_name': 'GBR', 'n_estimators_gb': 90, 'learning_rate_gb': 0.00023130612490239227}. Best is trial 2 with value: 0.07934790285463093.
[I 2026-06-21 19:35:07,262] Trial 15 finished with value: 0.07934790285463093 and parameters: {'model_name': 'LR'}. Best is trial 2 with value: 0.07934790285463093.

🏃 View run languid-cow-151 at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0/runs/de8c6f96767b4c1495b39f4002f1317e
🧪 View experiment at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0

[I 2026-06-21 19:35:23,442] Trial 16 finished with value: 0.07934790285463093 and parameters: {'model_name': 'LR'}. Best is trial 2 with value: 0.07934790285463093.

🏃 View run valuable-kit-720 at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0/runs/78f360d133a2408fb6354ef42e60a2c0
🧪 View experiment at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0
🏃 View run unleashed-eel-484 at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0/runs/6c1e7f4b45394f55a11afc59942f6326
🧪 View experiment at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0

[I 2026-06-21 19:35:43,301] Trial 18 finished with value: 0.07934790285463093 and parameters: {'model_name': 'LR'}. Best is trial 2 with value: 0.07934790285463093.
[I 2026-06-21 19:35:51,294] Trial 17 finished with value: 0.07934790285463093 and parameters: {'model_name': 'LR'}. Best is trial 2 with value: 0.07934790285463093.

🏃 View run aged-kit-478 at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0/runs/bb3c7df73e2e483d94e610426ecce399
🧪 View experiment at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0

[I 2026-06-21 19:35:53,524] Trial 7 finished with value: 0.23731730074450466 and parameters: {'model_name': 'RF', 'n_estimators_rf': 100, 'max_depth_rf': 5}. Best is trial 2 with value: 0.07934790285463093.

🏃 View run bold-bear-658 at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0/runs/9b1a704ab1044533b59822c19a953b41
🧪 View experiment at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0
🏃 View run popular-ant-953 at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0/runs/92e11ff872a6402198d7b3f3bf907585
🧪 View experiment at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0

[I 2026-06-21 19:36:24,091] Trial 21 finished with value: 0.07934790285463093 and parameters: {'model_name': 'LR'}. Best is trial 2 with value: 0.07934790285463093.

🏃 View run learned-sheep-227 at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0/runs/b1cfe2cf430342a48646cba1058c0d3e
🧪 View experiment at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0

[I 2026-06-21 19:36:31,290] Trial 19 finished with value: 0.07934790285463093 and parameters: {'model_name': 'LR'}. Best is trial 2 with value: 0.07934790285463093.

🏃 View run orderly-lynx-342 at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0/runs/4bdad349f9174593addf4b9cfe34d62d
🧪 View experiment at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0

[I 2026-06-21 19:36:43,292] Trial 20 finished with value: 0.07934790285463093 and parameters: {'model_name': 'LR'}. Best is trial 2 with value: 0.07934790285463093.

🏃 View run upset-pug-558 at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0/runs/fa2dd80b412a404e8dfb44757c0c499c
🧪 View experiment at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0

[I 2026-06-21 19:36:51,281] Trial 22 finished with value: 0.07934790285463093 and parameters: {'model_name': 'LR'}. Best is trial 2 with value: 0.07934790285463093.

🏃 View run adaptable-gnu-616 at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0/runs/987346e718e34e69b3e8926258dde48f
🧪 View experiment at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0

[I 2026-06-21 19:37:03,244] Trial 24 finished with value: 0.07934790285463093 and parameters: {'model_name': 'LR'}. Best is trial 2 with value: 0.07934790285463093.
[I 2026-06-21 19:37:11,310] Trial 23 finished with value: 0.07934790285463093 and parameters: {'model_name': 'LR'}. Best is trial 2 with value: 0.07934790285463093.

🏃 View run bedecked-frog-813 at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0/runs/88a26de75fe74d52955f8cc550f15b65
🧪 View experiment at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0
🏃 View run whimsical-dog-474 at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0/runs/8e44f604a7d34d04807f8f80c61cdb60
🧪 View experiment at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0
🏃 View run abrasive-whale-536 at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0/runs/79ba320bf3f845b6aea69df3c3442e31
🧪 View experiment at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0

[I 2026-06-21 19:37:24,130] Trial 26 finished with value: 0.07934790285463093 and parameters: {'model_name': 'LR'}. Best is trial 2 with value: 0.07934790285463093.
[I 2026-06-21 19:37:31,441] Trial 25 finished with value: 0.07934790285463093 and parameters: {'model_name': 'LR'}. Best is trial 2 with value: 0.07934790285463093.
[I 2026-06-21 19:37:35,369] Trial 27 finished with value: 0.07934790285463093 and parameters: {'model_name': 'LR'}. Best is trial 2 with value: 0.07934790285463093.

🏃 View run bustling-rat-638 at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0/runs/33c0e0a2383541b4bd2690612f7b84c4
🧪 View experiment at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0
🏃 View run youthful-wasp-997 at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0/runs/a1f980143d0641258e16d644d35ce887
🧪 View experiment at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0
🏃 View run unleashed-donkey-523 at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0/runs/6699af560a9046a5863b882851079597
🧪 View experiment at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0

[I 2026-06-21 19:38:19,090] Trial 29 finished with value: 0.5365101844163557 and parameters: {'model_name': 'RF', 'n_estimators_rf': 10, 'max_depth_rf': 3}. Best is trial 2 with value: 0.07934790285463093.
[I 2026-06-21 19:38:19,306] Trial 30 finished with value: 0.5365101844163557 and parameters: {'model_name': 'RF', 'n_estimators_rf': 10, 'max_depth_rf': 3}. Best is trial 2 with value: 0.07934790285463093.

🏃 View run traveling-gnat-669 at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0/runs/c06610c54d344d778f98efb8d2bc1a7f
🧪 View experiment at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0

[I 2026-06-21 19:38:23,328] Trial 31 finished with value: 2.8982344052068933 and parameters: {'model_name': 'GBR', 'n_estimators_gb': 10, 'learning_rate_gb': 0.08587121289699667}. Best is trial 2 with value: 0.07934790285463093.
[I 2026-06-21 19:38:31,287] Trial 28 finished with value: 0.07934790285463093 and parameters: {'model_name': 'LR'}. Best is trial 2 with value: 0.07934790285463093.

🏃 View run luxuriant-foal-828 at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0/runs/53b7af85887440c488693cf9f4133b0c
🧪 View experiment at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0

[I 2026-06-21 19:38:36,106] Trial 33 finished with value: 2.5883299705564715 and parameters: {'model_name': 'GBR', 'n_estimators_gb': 10, 'learning_rate_gb': 0.09724911427475559}. Best is trial 2 with value: 0.07934790285463093.

🏃 View run unleashed-auk-542 at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0/runs/e743eda88eda4c098fa564026f45e230
🧪 View experiment at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0
🏃 View run caring-doe-843 at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0/runs/b3b7b6038be143c7a978193bdf1661ae
🧪 View experiment at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0

[I 2026-06-21 19:38:55,392] Trial 36 finished with value: 0.07934790285463093 and parameters: {'model_name': 'LR'}. Best is trial 2 with value: 0.07934790285463093.

🏃 View run sedate-gull-607 at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0/runs/af1f59aa0fc047f39f5ca970b5d89e57
🧪 View experiment at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0

[I 2026-06-21 19:38:56,276] Trial 34 finished with value: 0.07934790285463093 and parameters: {'model_name': 'LR'}. Best is trial 2 with value: 0.07934790285463093.
[I 2026-06-21 19:38:59,338] Trial 32 finished with value: 0.07934790285463093 and parameters: {'model_name': 'LR'}. Best is trial 2 with value: 0.07934790285463093.

🏃 View run blushing-whale-211 at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0/runs/5814622189804c658caf4a07e3b931ac
🧪 View experiment at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0
🏃 View run thundering-ant-262 at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0/runs/be320914b2494d2882323416d2de26f5
🧪 View experiment at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0

[I 2026-06-21 19:39:27,964] Trial 37 finished with value: 2.659677028656006 and parameters: {'model_name': 'XGBR', 'n_estimators_xgb': 10, 'learning_rate_xgb': 0.08817473443727449, 'max_depth_xgb': 10}. Best is trial 2 with value: 0.07934790285463093.

🏃 View run smiling-skink-325 at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0/runs/33a8fb5f82bd47658a8b6ea926842fa2
🧪 View experiment at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0

[I 2026-06-21 19:39:35,303] Trial 35 finished with value: 0.07934790285463093 and parameters: {'model_name': 'LR'}. Best is trial 2 with value: 0.07934790285463093.

🏃 View run placid-wolf-209 at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0/runs/ae3ff93738e14483bb8af8434d84a635
🧪 View experiment at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0
🏃 View run auspicious-yak-150 at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0/runs/def2adfcfc034300a5e4dcbe474b143d
🧪 View experiment at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0

[I 2026-06-21 19:39:47,376] Trial 39 finished with value: 3.5203187465667725 and parameters: {'model_name': 'XGBR', 'n_estimators_xgb': 10, 'learning_rate_xgb': 0.06160451379423164, 'max_depth_xgb': 10}. Best is trial 2 with value: 0.07934790285463093.
[I 2026-06-21 19:39:55,471] Trial 41 finished with value: 0.2937488555908203 and parameters: {'model_name': 'XGBR', 'n_estimators_xgb': 40, 'learning_rate_xgb': 0.08045631740913305, 'max_depth_xgb': 10}. Best is trial 2 with value: 0.07934790285463093.
[I 2026-06-21 19:39:59,484] Trial 38 finished with value: 2.6000986099243164 and parameters: {'model_name': 'XGBR', 'n_estimators_xgb': 10, 'learning_rate_xgb': 0.09028896115639536, 'max_depth_xgb': 10}. Best is trial 2 with value: 0.07934790285463093.

🏃 View run classy-cod-371 at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0/runs/b6f9ee4ecc7c41528a9f8b6708b9b675
🧪 View experiment at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0

[I 2026-06-21 19:40:13,691] Trial 44 finished with value: 0.07934790285463093 and parameters: {'model_name': 'LR'}. Best is trial 2 with value: 0.07934790285463093.

🏃 View run omniscient-owl-675 at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0/runs/4c4f365816b74a8db996070cb16e98d7
🧪 View experiment at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0

[I 2026-06-21 19:40:19,456] Trial 42 finished with value: 0.12881554835626416 and parameters: {'model_name': 'RF', 'n_estimators_rf': 60, 'max_depth_rf': 10}. Best is trial 2 with value: 0.07934790285463093.

🏃 View run beautiful-stork-733 at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0/runs/e0cd9ac2e734473680aad5fe38cf94b1
🧪 View experiment at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0

[I 2026-06-21 19:40:22,440] Trial 43 finished with value: 0.12881554835626416 and parameters: {'model_name': 'RF', 'n_estimators_rf': 60, 'max_depth_rf': 10}. Best is trial 2 with value: 0.07934790285463093.

🏃 View run hilarious-deer-988 at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0/runs/b060fe322f464858855ab2f7a6d35f68
🧪 View experiment at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0

[I 2026-06-21 19:40:24,277] Trial 40 finished with value: 0.24896124005317688 and parameters: {'model_name': 'XGBR', 'n_estimators_xgb': 40, 'learning_rate_xgb': 0.08560380281457174, 'max_depth_xgb': 10}. Best is trial 2 with value: 0.07934790285463093.

🏃 View run gifted-colt-916 at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0/runs/37ac85904fb54f46a37d11079d692f30
🧪 View experiment at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0
🏃 View run loud-crane-497 at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0/runs/0da62f9f2c0b4831b1ee1a5451ae1422
🧪 View experiment at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0

[I 2026-06-21 19:40:44,143] Trial 45 finished with value: 0.07934790285463093 and parameters: {'model_name': 'LR'}. Best is trial 2 with value: 0.07934790285463093.
[I 2026-06-21 19:40:47,499] Trial 46 finished with value: 0.07934790285463093 and parameters: {'model_name': 'LR'}. Best is trial 2 with value: 0.07934790285463093.

🏃 View run exultant-shoat-608 at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0/runs/9059ca8793d347dfa7090a83b62b6c43
🧪 View experiment at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0

[I 2026-06-21 19:40:52,089] Trial 48 finished with value: 0.07934790285463093 and parameters: {'model_name': 'LR'}. Best is trial 2 with value: 0.07934790285463093.

🏃 View run fearless-stag-686 at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0/runs/ecb64389196d45eaaf73716d01a8942d
🧪 View experiment at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0

[I 2026-06-21 19:40:59,380] Trial 47 finished with value: 0.07934790285463093 and parameters: {'model_name': 'LR'}. Best is trial 2 with value: 0.07934790285463093.

🏃 View run angry-hen-555 at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0/runs/550a7938cece481ca8b159b98ca43223
🧪 View experiment at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0

[I 2026-06-21 19:41:16,267] Trial 49 finished with value: 5.685380787601503 and parameters: {'model_name': 'GBR', 'n_estimators_gb': 50, 'learning_rate_gb': 0.0031014818513940556}. Best is trial 2 with value: 0.07934790285463093.

🏃 View run best_model at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0/runs/8c68f900b9e1414c80f80413e5d4ec91
🧪 View experiment at: https://dagshub.com/mrvivekkumar7171/uber-demand-prediction.mlflow/#/experiments/0

In [18]:
# best value

study.best_value

0.07934790285463093

In [19]:
# best parameters

study.best_params

{'model_name': 'LR'}

In [20]:
# model value counts

study.trials_dataframe()['params_model_name'].value_counts()

params_model_name
LR      28
XGBR     9
RF       7
GBR      6
Name: count, dtype: int64

We can say that LR is our bast model with around 8% error. Mostly LR is used means LR is stable and best for the problem.

In [21]:
plot_optimization_history(study)

This shows that our model got optimized after 2 trails only

In [22]:
plot_parallel_coordinate(study, params=["model_name"])

LR is constantly giving low error. Thus training the best model alone again.

In [23]:
# train the linear regression model

lr = LinearRegression()

lr.fit(X_train_encoded, y_train)

# get predictions
y_pred_train = lr.predict(X_train_encoded) 
y_pred_test = lr.predict(X_test_encoded)

# loss

mape_train = mean_absolute_percentage_error(y_train, y_pred_train)
mape_test = mean_absolute_percentage_error(y_test, y_pred_test)

print("The training error is ", mape_train)
print("The test error is ", mape_test)

The training error is  0.08778013304566609
The test error is  0.07934790285463093

Again, we are getting the same error of 8%

In [24]:
# weights of the linear regression model
lr.coef_

array([-2.33737604,  0.71512405, -0.55601505, -1.25311068, -3.20463231,
       -0.86685973, -2.79925402, -3.62516859,  0.41386463, -2.9376376 ,
       -1.97624678, -3.75050442,  0.51806283, -2.54033388, -2.43297463,
        0.47632075,  0.61254786, -4.7417372 , -2.03077217, -1.26960984,
       -4.03690273, -2.08863167, -1.0414428 ,  0.73561736, -0.99999442,
       -0.85944985, -2.43098478,  0.67112238,  0.57385071, -0.11719951,
       -0.28045898, -0.37180749, -0.5238324 , -0.4233113 , -0.34045774,
       -0.54170892, -0.36264553, -0.2493965 , -0.31905518,  2.4912456 ])

### Ridge

In [25]:
def tune_ridge(trial):
    # hyperparameter space
    alpha = trial.suggest_float("alpha", 30, 100)
    
    # make the model object
    ridge = Ridge(alpha=alpha, random_state=42)
    
    # train the model
    ridge.fit(X_train_encoded, y_train)
    
    # get predictions
    y_pred = ridge.predict(X_test_encoded)
    
    # calculate loss
    loss = mean_absolute_percentage_error(y_test, y_pred)

    return loss

In [26]:
# create study

study = optuna.create_study(study_name="tune_model", direction="minimize")

[I 2026-06-21 19:41:20,167] A new study created in memory with name: tune_model

In [27]:
# optimize

study.optimize(func=tune_ridge, n_trials=100, n_jobs=-1, show_progress_bar=True)

Best trial: 3. Best value: 0.0791701:   3%|▎         | 3/100 [00:00<00:24,  3.98it/s]

[I 2026-06-21 19:41:20,411] Trial 0 finished with value: 0.07926979411635493 and parameters: {'alpha': 32.90993180270842}. Best is trial 0 with value: 0.07926979411635493.
[I 2026-06-21 19:41:20,427] Trial 1 finished with value: 0.07919400253867599 and parameters: {'alpha': 77.66603787869215}. Best is trial 1 with value: 0.07919400253867599.
[I 2026-06-21 19:41:20,436] Trial 2 finished with value: 0.0792432695613644 and parameters: {'alpha': 46.7747675300711}. Best is trial 1 with value: 0.07919400253867599.
[I 2026-06-21 19:41:20,437] Trial 3 finished with value: 0.07917014311112226 and parameters: {'alpha': 95.12849969750454}. Best is trial 3 with value: 0.07917014311112226.

Best trial: 3. Best value: 0.0791701:   7%|▋         | 7/100 [00:00<00:07, 12.00it/s]

[I 2026-06-21 19:41:20,638] Trial 4 finished with value: 0.07917963078674678 and parameters: {'alpha': 87.94074062128922}. Best is trial 3 with value: 0.07917014311112226.
[I 2026-06-21 19:41:20,649] Trial 5 finished with value: 0.07921005647132995 and parameters: {'alpha': 66.84769146142605}. Best is trial 3 with value: 0.07917014311112226.
[I 2026-06-21 19:41:20,711] Trial 6 finished with value: 0.07917551017505223 and parameters: {'alpha': 91.0181748013951}. Best is trial 3 with value: 0.07917014311112226.
[I 2026-06-21 19:41:20,747] Trial 7 finished with value: 0.07920982506381359 and parameters: {'alpha': 66.99937658254683}. Best is trial 3 with value: 0.07917014311112226.

Best trial: 11. Best value: 0.0791679:  11%|█         | 11/100 [00:00<00:06, 13.32it/s]

[I 2026-06-21 19:41:20,908] Trial 8 finished with value: 0.07920036838379155 and parameters: {'alpha': 73.3136174971295}. Best is trial 3 with value: 0.07917014311112226.
[I 2026-06-21 19:41:20,944] Trial 9 finished with value: 0.07923890108369856 and parameters: {'alpha': 49.232896452951465}. Best is trial 3 with value: 0.07917014311112226.
[I 2026-06-21 19:41:20,987] Trial 10 finished with value: 0.07920298764273814 and parameters: {'alpha': 71.54447413519787}. Best is trial 3 with value: 0.07917014311112226.
[I 2026-06-21 19:41:21,016] Trial 11 finished with value: 0.07916792955040748 and parameters: {'alpha': 96.88169223886423}. Best is trial 11 with value: 0.07916792955040748.

Best trial: 15. Best value: 0.0791645:  15%|█▌        | 15/100 [00:01<00:05, 14.25it/s]

[I 2026-06-21 19:41:21,148] Trial 12 finished with value: 0.07918451393103014 and parameters: {'alpha': 84.36011820791674}. Best is trial 11 with value: 0.07916792955040748.
[I 2026-06-21 19:41:21,159] Trial 13 finished with value: 0.07916806081113875 and parameters: {'alpha': 96.77719482684893}. Best is trial 11 with value: 0.07916792955040748.
[I 2026-06-21 19:41:21,221] Trial 14 finished with value: 0.0791649325192537 and parameters: {'alpha': 99.29400170914813}. Best is trial 14 with value: 0.0791649325192537.
[I 2026-06-21 19:41:21,262] Trial 15 finished with value: 0.07916450970986415 and parameters: {'alpha': 99.63822585579327}. Best is trial 15 with value: 0.07916450970986415.

Best trial: 16. Best value: 0.0791642:  19%|█▉        | 19/100 [00:01<00:05, 14.78it/s]

[I 2026-06-21 19:41:21,401] Trial 16 finished with value: 0.0791642375202533 and parameters: {'alpha': 99.85992077656363}. Best is trial 16 with value: 0.0791642375202533.
[I 2026-06-21 19:41:21,411] Trial 17 finished with value: 0.0791644226572565 and parameters: {'alpha': 99.70912478273925}. Best is trial 16 with value: 0.0791642375202533.
[I 2026-06-21 19:41:21,475] Trial 18 finished with value: 0.07916469572075506 and parameters: {'alpha': 99.48677080339878}. Best is trial 16 with value: 0.0791642375202533.
[I 2026-06-21 19:41:21,514] Trial 19 finished with value: 0.07918638969461408 and parameters: {'alpha': 83.01109485576923}. Best is trial 16 with value: 0.0791642375202533.

Best trial: 16. Best value: 0.0791642:  23%|██▎       | 23/100 [00:01<00:05, 15.17it/s]

[I 2026-06-21 19:41:21,682] Trial 20 finished with value: 0.07918785810035504 and parameters: {'alpha': 81.96764105007681}. Best is trial 16 with value: 0.0791642375202533.
[I 2026-06-21 19:41:21,707] Trial 21 finished with value: 0.0791863128521492 and parameters: {'alpha': 83.06611083161353}. Best is trial 16 with value: 0.0791642375202533.
[I 2026-06-21 19:41:21,729] Trial 22 finished with value: 0.07918583526095625 and parameters: {'alpha': 83.40886649310595}. Best is trial 16 with value: 0.0791642375202533.
[I 2026-06-21 19:41:21,766] Trial 23 finished with value: 0.07917759966517118 and parameters: {'alpha': 89.45106317188835}. Best is trial 16 with value: 0.0791642375202533.

Best trial: 16. Best value: 0.0791642:  28%|██▊       | 28/100 [00:01<00:03, 18.09it/s]

[I 2026-06-21 19:41:21,884] Trial 24 finished with value: 0.07917607815842284 and parameters: {'alpha': 90.59009057572695}. Best is trial 16 with value: 0.0791642375202533.
[I 2026-06-21 19:41:21,961] Trial 25 finished with value: 0.07917659138000502 and parameters: {'alpha': 90.20481027382255}. Best is trial 16 with value: 0.0791642375202533.
[I 2026-06-21 19:41:21,979] Trial 27 finished with value: 0.07917438069711652 and parameters: {'alpha': 91.87247885448498}. Best is trial 16 with value: 0.0791642375202533.
[I 2026-06-21 19:41:21,987] Trial 26 finished with value: 0.07917591486101541 and parameters: {'alpha': 90.71292752315489}. Best is trial 16 with value: 0.0791642375202533.

Best trial: 31. Best value: 0.0791641:  31%|███       | 31/100 [00:02<00:04, 15.49it/s]

[I 2026-06-21 19:41:22,161] Trial 28 finished with value: 0.07917226699483196 and parameters: {'alpha': 93.48334023643103}. Best is trial 16 with value: 0.0791642375202533.
[I 2026-06-21 19:41:22,209] Trial 29 finished with value: 0.07917086228203722 and parameters: {'alpha': 94.56736042448651}. Best is trial 16 with value: 0.0791642375202533.
[I 2026-06-21 19:41:22,236] Trial 30 finished with value: 0.07917021397208605 and parameters: {'alpha': 95.07314081310955}. Best is trial 16 with value: 0.0791642375202533.
[I 2026-06-21 19:41:22,242] Trial 31 finished with value: 0.07916409434141135 and parameters: {'alpha': 99.9765539513445}. Best is trial 31 with value: 0.07916409434141135.

Best trial: 31. Best value: 0.0791641:  35%|███▌      | 35/100 [00:02<00:04, 14.90it/s]

[I 2026-06-21 19:41:22,426] Trial 32 finished with value: 0.079164327766275 and parameters: {'alpha': 99.78641217978164}. Best is trial 31 with value: 0.07916409434141135.
[I 2026-06-21 19:41:22,449] Trial 33 finished with value: 0.0792565396816233 and parameters: {'alpha': 39.660656941969165}. Best is trial 31 with value: 0.07916409434141135.
[I 2026-06-21 19:41:22,459] Trial 34 finished with value: 0.07916420490141896 and parameters: {'alpha': 99.8864910486015}. Best is trial 31 with value: 0.07916409434141135.
[I 2026-06-21 19:41:22,514] Trial 35 finished with value: 0.07916428015522242 and parameters: {'alpha': 99.82519253670694}. Best is trial 31 with value: 0.07916409434141135.

Best trial: 31. Best value: 0.0791641:  39%|███▉      | 39/100 [00:02<00:03, 16.38it/s]

[I 2026-06-21 19:41:22,647] Trial 36 finished with value: 0.07927225582275663 and parameters: {'alpha': 31.697493516812912}. Best is trial 31 with value: 0.07916409434141135.
[I 2026-06-21 19:41:22,736] Trial 37 finished with value: 0.07918032490713973 and parameters: {'alpha': 87.42697322404061}. Best is trial 31 with value: 0.07916409434141135.
[I 2026-06-21 19:41:22,739] Trial 38 finished with value: 0.07918239344528182 and parameters: {'alpha': 85.90330336015045}. Best is trial 31 with value: 0.07916409434141135.
[I 2026-06-21 19:41:22,743] Trial 39 finished with value: 0.07918107124037552 and parameters: {'alpha': 86.87573259849846}. Best is trial 31 with value: 0.07916409434141135.

Best trial: 31. Best value: 0.0791641:  43%|████▎     | 43/100 [00:02<00:03, 15.46it/s]

[I 2026-06-21 19:41:22,869] Trial 40 finished with value: 0.07919159332507587 and parameters: {'alpha': 79.34360123562423}. Best is trial 31 with value: 0.07916409434141135.
[I 2026-06-21 19:41:22,948] Trial 41 finished with value: 0.0791912781665242 and parameters: {'alpha': 79.56429478732876}. Best is trial 31 with value: 0.07916409434141135.
[I 2026-06-21 19:41:23,018] Trial 43 finished with value: 0.07919250570891254 and parameters: {'alpha': 78.70531977222521}. Best is trial 31 with value: 0.07916409434141135.
[I 2026-06-21 19:41:23,041] Trial 42 finished with value: 0.0791704896589614 and parameters: {'alpha': 94.85778837745806}. Best is trial 31 with value: 0.07916409434141135.

Best trial: 31. Best value: 0.0791641:  48%|████▊     | 48/100 [00:03<00:03, 17.08it/s]

[I 2026-06-21 19:41:23,114] Trial 44 finished with value: 0.07916951567901737 and parameters: {'alpha': 95.6218930375707}. Best is trial 31 with value: 0.07916409434141135.
[I 2026-06-21 19:41:23,190] Trial 45 finished with value: 0.07916991009014834 and parameters: {'alpha': 95.31069247064826}. Best is trial 31 with value: 0.07916409434141135.
[I 2026-06-21 19:41:23,268] Trial 46 finished with value: 0.07916899711932417 and parameters: {'alpha': 96.03349581641343}. Best is trial 31 with value: 0.07916409434141135.
[I 2026-06-21 19:41:23,280] Trial 47 finished with value: 0.07916851295002446 and parameters: {'alpha': 96.41794701570427}. Best is trial 31 with value: 0.07916409434141135.

Best trial: 31. Best value: 0.0791641:  51%|█████     | 51/100 [00:03<00:02, 17.13it/s]

[I 2026-06-21 19:41:23,362] Trial 48 finished with value: 0.07916758163504047 and parameters: {'alpha': 97.15930829290956}. Best is trial 31 with value: 0.07916409434141135.
[I 2026-06-21 19:41:23,410] Trial 49 finished with value: 0.0791671817343354 and parameters: {'alpha': 97.4788290264369}. Best is trial 31 with value: 0.07916409434141135.
[I 2026-06-21 19:41:23,533] Trial 51 finished with value: 0.07922745355218085 and parameters: {'alpha': 55.934621865894854}. Best is trial 31 with value: 0.07916409434141135.
[I 2026-06-21 19:41:23,534] Trial 50 finished with value: 0.07921842831853323 and parameters: {'alpha': 61.48381632751718}. Best is trial 31 with value: 0.07916409434141135.

Best trial: 31. Best value: 0.0791641:  55%|█████▌    | 55/100 [00:03<00:02, 15.16it/s]

[I 2026-06-21 19:41:23,617] Trial 52 finished with value: 0.07916433689044484 and parameters: {'alpha': 99.77898046023827}. Best is trial 31 with value: 0.07916409434141135.
[I 2026-06-21 19:41:23,646] Trial 53 finished with value: 0.07922566177090083 and parameters: {'alpha': 57.01397207462808}. Best is trial 31 with value: 0.07916409434141135.
[I 2026-06-21 19:41:23,777] Trial 54 finished with value: 0.07917267370603207 and parameters: {'alpha': 93.17191836946216}. Best is trial 31 with value: 0.07916409434141135.
[I 2026-06-21 19:41:23,807] Trial 55 finished with value: 0.07916432202115714 and parameters: {'alpha': 99.79109165446313}. Best is trial 31 with value: 0.07916409434141135.

Best trial: 57. Best value: 0.0791641:  60%|██████    | 60/100 [00:03<00:02, 15.81it/s]

[I 2026-06-21 19:41:23,867] Trial 56 finished with value: 0.07916458280409364 and parameters: {'alpha': 99.57870268757301}. Best is trial 31 with value: 0.07916409434141135.
[I 2026-06-21 19:41:23,894] Trial 57 finished with value: 0.07916406791899547 and parameters: {'alpha': 99.99807879059418}. Best is trial 57 with value: 0.07916406791899547.
[I 2026-06-21 19:41:24,045] Trial 58 finished with value: 0.07916463493865018 and parameters: {'alpha': 99.53625613178525}. Best is trial 57 with value: 0.07916406791899547.
[I 2026-06-21 19:41:24,046] Trial 59 finished with value: 0.07916416900338817 and parameters: {'alpha': 99.91573310355746}. Best is trial 57 with value: 0.07916406791899547.

Best trial: 57. Best value: 0.0791641:  63%|██████▎   | 63/100 [00:04<00:02, 14.60it/s]

[I 2026-06-21 19:41:24,125] Trial 60 finished with value: 0.07917330563012549 and parameters: {'alpha': 92.68886658119193}. Best is trial 57 with value: 0.07916406791899547.
[I 2026-06-21 19:41:24,150] Trial 61 finished with value: 0.07917444736591163 and parameters: {'alpha': 91.82199446811715}. Best is trial 57 with value: 0.07916406791899547.
[I 2026-06-21 19:41:24,294] Trial 62 finished with value: 0.07917297558783148 and parameters: {'alpha': 92.94089103463772}. Best is trial 57 with value: 0.07916406791899547.

[I 2026-06-21 19:41:24,360] Trial 63 finished with value: 0.07917347632069871 and parameters: {'alpha': 92.55903987563295}. Best is trial 57 with value: 0.07916406791899547.
[I 2026-06-21 19:41:24,374] Trial 64 finished with value: 0.07916683687671433 and parameters: {'alpha': 97.75611233822802}. Best is trial 57 with value: 0.07916406791899547.
[I 2026-06-21 19:41:24,410] Trial 65 finished with value: 0.07916687667853148 and parameters: {'alpha': 97.72405897761043}. Best is trial 57 with value: 0.07916406791899547.
[I 2026-06-21 19:41:24,547] Trial 66 finished with value: 0.07916703077829537 and parameters: {'alpha': 97.600020873531}. Best is trial 57 with value: 0.07916406791899547.

Best trial: 57. Best value: 0.0791641:  69%|██████▉   | 69/100 [00:04<00:02, 15.25it/s]

[I 2026-06-21 19:41:24,558] Trial 67 finished with value: 0.07916690980343499 and parameters: {'alpha': 97.69738573364654}. Best is trial 57 with value: 0.07916406791899547.
[I 2026-06-21 19:41:24,618] Trial 68 finished with value: 0.0791781056731017 and parameters: {'alpha': 89.07398644098076}. Best is trial 57 with value: 0.07916406791899547.
[I 2026-06-21 19:41:24,666] Trial 69 finished with value: 0.07917782942509771 and parameters: {'alpha': 89.27981871177552}. Best is trial 57 with value: 0.07916406791899547.

Best trial: 57. Best value: 0.0791641:  73%|███████▎  | 73/100 [00:04<00:01, 15.22it/s]

[I 2026-06-21 19:41:24,801] Trial 70 finished with value: 0.07917733313356505 and parameters: {'alpha': 89.64988255183682}. Best is trial 57 with value: 0.07916406791899547.
[I 2026-06-21 19:41:24,890] Trial 71 finished with value: 0.0791777479655886 and parameters: {'alpha': 89.34052602036212}. Best is trial 57 with value: 0.07916406791899547.
[I 2026-06-21 19:41:24,901] Trial 72 finished with value: 0.07917128312394986 and parameters: {'alpha': 94.24091285372377}. Best is trial 57 with value: 0.07916406791899547.
[I 2026-06-21 19:41:24,917] Trial 73 finished with value: 0.07917046869666818 and parameters: {'alpha': 94.87416175146815}. Best is trial 57 with value: 0.07916406791899547.

Best trial: 57. Best value: 0.0791641:  77%|███████▋  | 77/100 [00:05<00:01, 13.66it/s]

[I 2026-06-21 19:41:25,070] Trial 74 finished with value: 0.07916423295066373 and parameters: {'alpha': 99.86364298649345}. Best is trial 57 with value: 0.07916406791899547.
[I 2026-06-21 19:41:25,192] Trial 75 finished with value: 0.07916469016093919 and parameters: {'alpha': 99.49129720683257}. Best is trial 57 with value: 0.07916406791899547.
[I 2026-06-21 19:41:25,233] Trial 76 finished with value: 0.079164474341034 and parameters: {'alpha': 99.66703107826649}. Best is trial 57 with value: 0.07916406791899547.
[I 2026-06-21 19:41:25,243] Trial 77 finished with value: 0.07916408585396485 and parameters: {'alpha': 99.98346815084635}. Best is trial 57 with value: 0.07916406791899547.

Best trial: 57. Best value: 0.0791641:  79%|███████▉  | 79/100 [00:05<00:01, 12.47it/s]

[I 2026-06-21 19:41:25,443] Trial 78 finished with value: 0.07916654868441421 and parameters: {'alpha': 97.9882481414676}. Best is trial 57 with value: 0.07916406791899547.

Best trial: 57. Best value: 0.0791641:  82%|████████▏ | 82/100 [00:05<00:01,  9.59it/s]

[I 2026-06-21 19:41:25,733] Trial 79 finished with value: 0.07916686708622123 and parameters: {'alpha': 97.7317838182844}. Best is trial 57 with value: 0.07916406791899547.
[I 2026-06-21 19:41:25,737] Trial 81 finished with value: 0.07916893959963539 and parameters: {'alpha': 96.07916171997459}. Best is trial 57 with value: 0.07916406791899547.
[I 2026-06-21 19:41:25,779] Trial 80 finished with value: 0.0791692755724707 and parameters: {'alpha': 95.81245115694587}. Best is trial 57 with value: 0.07916406791899547.
[I 2026-06-21 19:41:25,811] Trial 82 finished with value: 0.07916941154163461 and parameters: {'alpha': 95.70453049062903}. Best is trial 57 with value: 0.07916406791899547.

Best trial: 57. Best value: 0.0791641:  86%|████████▌ | 86/100 [00:05<00:01, 11.60it/s]

[I 2026-06-21 19:41:26,012] Trial 84 finished with value: 0.07917173932426687 and parameters: {'alpha': 93.88815287363037}. Best is trial 57 with value: 0.07916406791899547.
[I 2026-06-21 19:41:26,040] Trial 83 finished with value: 0.07917167689576449 and parameters: {'alpha': 93.9361384441073}. Best is trial 57 with value: 0.07916406791899547.
[I 2026-06-21 19:41:26,122] Trial 86 finished with value: 0.07917175947497981 and parameters: {'alpha': 93.87268122820907}. Best is trial 57 with value: 0.07916406791899547.
[I 2026-06-21 19:41:26,133] Trial 85 finished with value: 0.07917133670975825 and parameters: {'alpha': 94.19935589250301}. Best is trial 57 with value: 0.07916406791899547.

Best trial: 57. Best value: 0.0791641:  91%|█████████ | 91/100 [00:06<00:00, 13.91it/s]

[I 2026-06-21 19:41:26,315] Trial 87 finished with value: 0.07926324552652664 and parameters: {'alpha': 36.198735945855006}. Best is trial 57 with value: 0.07916406791899547.
[I 2026-06-21 19:41:26,342] Trial 88 finished with value: 0.07917483474577436 and parameters: {'alpha': 91.52869929379769}. Best is trial 57 with value: 0.07916406791899547.
[I 2026-06-21 19:41:26,397] Trial 89 finished with value: 0.07916618317810971 and parameters: {'alpha': 98.28277085183643}. Best is trial 57 with value: 0.07916406791899547.
[I 2026-06-21 19:41:26,456] Trial 90 finished with value: 0.07917520395242479 and parameters: {'alpha': 91.24935153172407}. Best is trial 57 with value: 0.07916406791899547.

Best trial: 57. Best value: 0.0791641:  94%|█████████▍| 94/100 [00:06<00:00, 12.21it/s]

[I 2026-06-21 19:41:26,597] Trial 91 finished with value: 0.07917538328310032 and parameters: {'alpha': 91.11396347735457}. Best is trial 57 with value: 0.07916406791899547.
[I 2026-06-21 19:41:26,660] Trial 93 finished with value: 0.07916413887225207 and parameters: {'alpha': 99.94027805473607}. Best is trial 57 with value: 0.07916406791899547.
[I 2026-06-21 19:41:26,666] Trial 92 finished with value: 0.07916673952019775 and parameters: {'alpha': 97.83451942663798}. Best is trial 57 with value: 0.07916406791899547.
[I 2026-06-21 19:41:26,721] Trial 94 finished with value: 0.0791642899062411 and parameters: {'alpha': 99.81724999596211}. Best is trial 57 with value: 0.07916406791899547.

Best trial: 57. Best value: 0.0791641: 100%|██████████| 100/100 [00:06<00:00, 14.58it/s]

[I 2026-06-21 19:41:26,849] Trial 95 finished with value: 0.07916439304245243 and parameters: {'alpha': 99.73324511874397}. Best is trial 57 with value: 0.07916406791899547.
[I 2026-06-21 19:41:26,928] Trial 96 finished with value: 0.07916416827639253 and parameters: {'alpha': 99.91632531239266}. Best is trial 57 with value: 0.07916406791899547.
[I 2026-06-21 19:41:26,937] Trial 97 finished with value: 0.07916860720472464 and parameters: {'alpha': 96.34309427059972}. Best is trial 57 with value: 0.07916406791899547.
[I 2026-06-21 19:41:26,994] Trial 98 finished with value: 0.07916408567942186 and parameters: {'alpha': 99.98361034220684}. Best is trial 57 with value: 0.07916406791899547.
[I 2026-06-21 19:41:27,039] Trial 99 finished with value: 0.07916908282967133 and parameters: {'alpha': 95.9654520304162}. Best is trial 57 with value: 0.07916406791899547.

In [28]:
# best parameters

study.best_params

{'alpha': 99.99807879059418}

In [29]:
# best value

study.best_value

0.07916406791899547

error is same as LR. Hence, we are going with LR as our final model.